# Generated by Django 3.1.5 on 2021-01-12 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsession',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
